feat: Add pvc support to couchbase helm
theappnest/gs-helm-charts pull request #3
Opened 2022-01-12 15:25 UTC by psawantdrest

2022-01-12 16:41 UTC, SamTealeDrest requested changes
Looks good, a few bits mentioned inline. We will also need a volume mount and volume declaring in the deployment.yaml template

2022-01-12 16:41 UTC, SamTealeDrest commented on charts/couchbase/templates/pvc.yaml
> +{{- if .Values.pvc.create -}}
Can we make this persistence.enabled format to match most of upstream charts?

2022-01-12 16:41 UTC, SamTealeDrest commented on charts/couchbase/templates/pvc.yaml
> +  storageClassName: {{ .Values.pvc.storageClass }}
This should be wrapped in an if and not set if empty so k8s will use default storage class

2022-01-12 18:15 UTC, psawantdrest commented
> Looks good, a few bits mentioned inline. We will also need a volume mount and volume declaring in the deployment.yaml template

What should be the values for mountPath and name under volumeMounts

2022-01-13 10:26 UTC, psawantdrest commented on charts/couchbase/templates/pvc.yaml
> +{{- if .Values.pvc.create -}}
modified it to enabled

2022-01-26 11:03 UTC, SamTealeDrest approved these changes

2022-01-26 11:04 UTC, merged